import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-4xl mx-auto">
          <div id="header" className="flex justify-between items-center py-5">
            <div id="header-left" className="flex items-center gap-4">
              <Image
                src="/deta.png"
                alt="profile image"
                width={70}
                height={70}
              />
              <div id="tagline">
                <Link href="/" className="text-xl font-bold">
                  I Putu Deta Utama Putra
                </Link>
                <p>A blog on JavaScript, web and more</p>
              </div>
            </div>
            <div id="header-right" className="flex gap-4">
              <a href="#docs">Docs</a>
              <a href="#github">GitHub</a>
              <Image
                src="images/search.svg"
                alt="search icon"
                width={20}
                height={20}
              />
            </div>
          </div>
          <div id="divider" className="mb-6">
            <div className="default_bg w-full rounded-md flex justify-center gap-11 py-1 text-xs font-bold">
              <Link href="#">JavaScript</Link>
              <Link href="#">Web Dev</Link>
            </div>
          </div>
          <div className="flex gap-4">
            <div className="w-3/4">{children}</div>
            <div id="sidebar" className="w-1/4 flex flex-col gap-4">
              <div className="border-4 border-lime-800 rounded-md">
                <div className="bg-lime-800 text-white p-2">
                  <h2 className="font-bold">Top Categories</h2>
                </div>
                <ul className="p-2 flex flex-wrap gap-1">
                  <li className="bg-lime-700 p-1 rounded-md text-white text-xs font-bold">
                    <Link href="#">JavaScript</Link>
                  </li>
                  <li className="bg-lime-700 p-1 rounded-md text-white text-xs font-bold">
                    <Link href="#">Web Dev</Link>
                  </li>
                  <li className="bg-lime-700 p-1 rounded-md text-white text-xs font-bold">
                    <Link href="#">React</Link>
                  </li>
                  <li className="bg-lime-700 p-1 rounded-md text-white text-xs font-bold">
                    <Link href="#">Next.js</Link>
                  </li>
                  <li className="bg-lime-700 p-1 rounded-md text-white text-xs font-bold">
                    <Link href="#">Tailwind CSS</Link>
                  </li>
                </ul>
              </div>
              <div className="h-48 border-4 border-lime-800 rounded-md">
                Other things to promote
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
